### ISSUE TITLE
(Phase 2) #2.3 ITP Project Plan Document

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ITP-Dashboard#6]
Task information:
Fill in the document for ITP project planning based on the guideline given on LMS site
As seen on the guideline...
Deliverables:

- [x] Firstly, the overarching objective(s) for the project must be clearly stated, and ideally in order
of priority. These objectives must be complex enough to decompose into sets of tasks. Each
set of tasks must specifically fulfill objective(s).

- [x] The plan shall be assessed on how comprehensive the combined sets of tasks are; i.e., tasks
ought to cover the duration of the project and lead to the fulfillment of its objectives.

- [x] There must be a diagram that illustrates the workflow order of all tasks, specifically involving
time estimates and whether tasks are dependent or can be achieved independently, in parallel
(recommendation is a Gantt chart).
o This diagram does not need to be highly detailed. A general overview is fine. A more
detailed version of the diagram may be linked to, or included in appendices, if needed.

- [x] Finally, there must be a section describing the team’s organizational structure and specific
roles of each member—roles may overlap. Roles must be described in detail and cover the
full set of responsibilities for each team member.

Task Deadline: 21/05/2023
Document submission is by then as well

To be done by:
Everybody

**Comment by LawJunHao** [comment]
Uploaded the final revision on LMS
